version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      # Use a named volume for node_modules to prevent overwriting by the mounted directory
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run serve

volumes:
  node_modules: 