version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    # Add health checks for production readiness
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Explicitly set user to non-root
    user: "1000:1000"
 