backup:
  storage:
    type: local
    local:
      directory: data/backups
    s3:
      bucket: ''
      prefix: backups/
  format: '{host}_config.txt'
  git:
    enabled: false
    author_name: NetRaven
    author_email: netraven@example.com
logging:
  level: INFO
  directory: logs
  filename: netraven.log
  # Retention policy settings
  retention_days: 30
  use_database_logging: true
  log_to_file: false
  console:
    enabled: true
    level: INFO
  file:
    enabled: true
    level: DEBUG
    max_size_mb: 10
    backup_count: 5
    # Time-based rotation settings (optional)
    # Uncomment to enable time-based rotation instead of size-based
    # rotation_when: midnight  # Options: S, M, H, D, midnight, W0-W6
    # rotation_interval: 1     # Interval multiplier for the rotation_when value
  json:
    enabled: false
    filename: netraven.json.log
    max_size_mb: 10
    backup_count: 5
    # Time-based rotation settings (same as file)
    # rotation_when: midnight
    # rotation_interval: 1
  sensitive_data:
    redact_enabled: true
  components:
    enabled: true
    level: DEBUG
    max_size_mb: 10
    backup_count: 5
    # Time-based rotation settings (same as file)
    # rotation_when: midnight
    # rotation_interval: 1
    files:
      frontend: frontend.log
      backend: backend.log
      jobs: jobs.log
      auth: auth.log
gateway:
  url: http://localhost:8001
  api_key: netraven-scheduler-key
  # Whether to use the gateway for device operations by default
  use_by_default: false
  # Timeout settings
  connect_timeout: 30
  command_timeout: 60
  # Retry settings
  max_retries: 3
  retry_delay: 5
web:
  host: 0.0.0.0
  port: 8000
  debug: true
  allowed_origins:
    - "*"
  database:
    type: postgres
    postgres:
      host: postgres
      port: 5432
      database: netraven
      user: netraven
      password: netraven
  authentication:
    token_expiration: 86400
    jwt_algorithm: HS256
