services:
  # Backend API service
  api:
    image: python:3.10-slim
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "cd /app && 
      pip install -e . &&
      pip install email-validator &&
      uvicorn netraven.web:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///netraven.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: ./netraven/web/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./netraven/web/frontend:/app
      # Use a named volume for node_modules to prevent overwriting
      - frontend_node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      - VUE_APP_API_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Non-root user for security
    user: "1001:1001"

volumes:
  frontend_node_modules: 