services:
  # PostgreSQL database service
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=netraven
      - POSTGRES_PASSWORD=netraven
      - POSTGRES_DB=netraven
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netraven"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Backend API service
  api:
    image: python:3.10-slim
    volumes:
      - .:/app
      - logs_data:/app/logs
    working_dir: /app
    command: >
      bash -c "cd /app && \
      apt-get update && \
      apt-get install -y curl postgresql-client && \
      pip install -e . && \
      pip install email-validator psycopg2-binary alembic schedule && \
      python -m netraven.web.migrations.run_migrations && \
      python -m netraven.web.migrations.test_migrations && \
      uvicorn netraven.web:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://netraven:netraven@postgres:5432/netraven
      - NETRAVEN_WEB_DB_TYPE=postgres
      - NETRAVEN_WEB_DB_HOST=postgres
      - NETRAVEN_WEB_DB_PORT=5432
      - NETRAVEN_WEB_DB_NAME=netraven
      - NETRAVEN_WEB_DB_USER=netraven
      - NETRAVEN_WEB_DB_PASSWORD=netraven
      - NETRAVEN_CONFIG=/app/config.yml
      - NETRAVEN_LOGGING_RETENTION_DAYS=30
      - NETRAVEN_LOGGING_USE_DATABASE=true
      - NETRAVEN_LOGGING_LOG_TO_FILE=false
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Scheduler service
  scheduler:
    image: python:3.10-slim
    volumes:
      - .:/app
      - logs_data:/app/logs
    working_dir: /app
    command: >
      bash -c "cd /app && \
      apt-get update && \
      apt-get install -y postgresql-client && \
      pip install -e . && \
      pip install psycopg2-binary schedule email-validator && \
      python scripts/run_scheduler.py --check-interval 60 --sync-interval 300 --log-level INFO"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://netraven:netraven@postgres:5432/netraven
      - NETRAVEN_WEB_DB_TYPE=postgres
      - NETRAVEN_WEB_DB_HOST=postgres
      - NETRAVEN_WEB_DB_PORT=5432
      - NETRAVEN_WEB_DB_NAME=netraven
      - NETRAVEN_WEB_DB_USER=netraven
      - NETRAVEN_WEB_DB_PASSWORD=netraven
      - NETRAVEN_CONFIG=/app/config.yml
      - NETRAVEN_LOGGING_RETENTION_DAYS=30
      - NETRAVEN_LOGGING_USE_DATABASE=true
      - NETRAVEN_LOGGING_LOG_TO_FILE=false
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./netraven/web/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./netraven/web/frontend:/app
      # Use a named volume for node_modules to prevent overwriting
      - frontend_node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      - VUE_APP_API_URL=http://api:8000
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Non-root user for security
    user: "1001:1001"

volumes:
  frontend_node_modules:
  postgres_data:
  logs_data: 