version: '3.7'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=netraven
      - POSTGRES_PASSWORD=netraven
      - POSTGRES_DB=netraven
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netraven"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://netraven:netraven@postgres:5432/netraven
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY:-netraven-dev-secret-key}
      - TOKEN_EXPIRY_HOURS=${TOKEN_EXPIRY_HOURS:-24}
      - SETUP_ADMIN_TOKEN=${SETUP_ADMIN_TOKEN:-true}
      - TOKEN_FILE=/app/tokens.json
      - TOKEN_STORE_TYPE=database
      - TOKEN_STORE_DATABASE_URL=postgresql://netraven:netraven@postgres:5432/netraven
    volumes:
      - ./netraven:/app/netraven
      - token_data:/app/tokens
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - netraven-network

  # Scheduler service
  scheduler:
    image: python:3.10-slim
    volumes:
      - .:/app
      - logs_data:/app/logs
    working_dir: /app
    command: >
      bash -c "cd /app && \
      apt-get update && \
      apt-get install -y postgresql-client curl && \
      pip install -e . && \
      pip install psycopg2-binary schedule email-validator requests sqlalchemy pydantic python-jose python-multipart prometheus-client pyjwt && \
      python scripts/run_scheduler.py --check-interval 60 --sync-interval 300 --log-level INFO --use-gateway"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://netraven:netraven@postgres:5432/netraven
      - NETRAVEN_WEB_DB_TYPE=postgres
      - NETRAVEN_WEB_DB_HOST=postgres
      - NETRAVEN_WEB_DB_PORT=5432
      - NETRAVEN_WEB_DB_NAME=netraven
      - NETRAVEN_WEB_DB_USER=netraven
      - NETRAVEN_WEB_DB_PASSWORD=netraven
      - NETRAVEN_CONFIG=/app/config.yml
      - NETRAVEN_LOGGING_RETENTION_DAYS=30
      - NETRAVEN_LOGGING_USE_DATABASE=true
      - NETRAVEN_LOGGING_LOG_TO_FILE=false
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY:-netraven-dev-secret-key}
      - GATEWAY_URL=http://device_gateway:8001
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
      device_gateway:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - netraven-network

  # Device Gateway service
  device_gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8001:8001"
    volumes:
      - ./netraven:/app/netraven
      - token_data:/app/tokens
    environment:
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY:-netraven-dev-secret-key}
      - GATEWAY_PORT=8001
      - TOKEN_STORE_TYPE=database
      - TOKEN_STORE_DATABASE_URL=postgresql://netraven:netraven@postgres:5432/netraven
      - TOKEN_FILE=/app/tokens.json
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    networks:
      - netraven-network

  # Frontend service
  frontend:
    build:
      context: ./netraven/web/frontend
      dockerfile: Dockerfile
    volumes:
      - ./netraven/web/frontend:/app
      # Use a named volume for node_modules to prevent overwriting
      - frontend_node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - api
      - device_gateway
    environment:
      - VUE_APP_API_URL=http://localhost:8000
      - VUE_APP_GATEWAY_URL=http://localhost:8001
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Non-root user for security
    user: "1001:1001"
    networks:
      - netraven-network

volumes:
  frontend_node_modules:
  postgres_data:
  logs_data:
  token_data:

networks:
  netraven-network:
    driver: bridge 