FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY frontend/package*.json ./
RUN npm ci
RUN npm install dayjs

# Copy the rest of the application
COPY frontend/. .

EXPOSE 5173

CMD ["npm", "run", "dev"] 