# Production Environment Configuration for NetRaven

database:
  # Standard PostgreSQL connection URL
  # Format: postgresql+<driver>://<user>:<password>@<host>:<port>/<database>
  url: "postgresql+psycopg2://netraven:netraven@postgres:5432/netraven"

scheduler:
  # URL for the Redis instance used by RQ and RQ Scheduler
  redis_url: "redis://redis:6379/0"
  # How often the scheduler checks for new jobs to sync from the DB (seconds)
  polling_interval_seconds: 60
  # Maximum number of retries for a failed job
  max_retries: 3
  # Base delay between retries (seconds) - RQ uses exponential backoff
  retry_backoff_seconds: 10

worker:
  # Number of concurrent device connections allowed per job run
  thread_pool_size: 10
  # Timeout for establishing a connection to a device (seconds)
  connection_timeout: 30
  # Number of attempts to connect/run commands if the first fails
  retry_attempts: 3
  # Delay between retry attempts (seconds)
  retry_backoff: 5
  # List of patterns/keywords to redact from device output logs
  redaction:
    patterns:
      - "password"
      - "secret"
      - "community"
      # Add more sensitive patterns as needed

logging:
  # Default logging level for the application
  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  redis:
    enabled: true
    host: redis
    port: 6379
    db: 0
    password: null
    channel_prefix: netraven-logs

# API Service specific settings
api:
  # Secret key for signing JWT tokens. IMPORTANT: Load from env var in production!
  jwt_secret: "${NETRAVEN_API__JWT_SECRET}"
  # Algorithm used for JWT signing
  jwt_algorithm: "HS256"
  # Token expiry time in minutes
  access_token_expire_minutes: 30

# Git Repository settings
git:
  # Path to the local directory where device configurations will be stored as a Git repo
  repo_path: "/data/git-config-repo" # Mount as a volume in production 