"""Add device_id to JobLog model

Revision ID: efed1e960ea3
Revises: a3992da91329
Create Date: 2025-04-06 16:12:11.656396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efed1e960ea3'
down_revision: Union[str, None] = 'a3992da91329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_logs', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_job_logs_device_id'), 'job_logs', ['device_id'], unique=False)
    op.create_foreign_key(None, 'job_logs', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_logs', type_='foreignkey')
    op.drop_index(op.f('ix_job_logs_device_id'), table_name='job_logs')
    op.drop_column('job_logs', 'device_id')
    # ### end Alembic commands ###
