# This file contains overrides for the test environment configuration.
# It is automatically loaded by docker-compose when present.

services:
  api:
    build:
      args:
        - NETRAVEN_ENV=test
    environment:
      - NETRAVEN_ENV=test
      # Test environment variables
      - UI_TEST_URL=http://frontend:8080
      - API_TEST_URL=http://api:8000
      - ADMIN_TEST_USER=admin
      - ADMIN_TEST_PASSWORD=NetRaven
      - TEST_TIMEOUT=10000
      # Ensure PostgreSQL is used for test environment
      - DATABASE_URL=postgresql://netraven:netraven@postgres:5432/netraven
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=netraven
      - POSTGRES_PASSWORD=netraven
      - POSTGRES_DB=netraven
      - NETRAVEN_WEB_DATABASE_TYPE=postgres
    volumes:
      # Mount the test artifacts directory for sharing test results
      - ./test-artifacts:/app/test-artifacts
      # Mount the tests directory for easier development and debugging
      - ./tests:/app/tests

  device_gateway:
    build:
      args:
        - NETRAVEN_ENV=test
    environment:
      - NETRAVEN_ENV=test

  frontend:
    build:
      args:
        - NETRAVEN_ENV=test
    environment:
      - NETRAVEN_ENV=test

  scheduler:
    command: bash -c "cd /app && python -m netraven.jobs.scheduler"
    environment:
      - NETRAVEN_ENV=test