# Security Headers Configuration

# Prevent MIME type sniffing
add_header X-Content-Type-Options "nosniff" always;

# Enable XSS filtering
add_header X-XSS-Protection "1; mode=block" always;

# Restrict iframe usage to same origin
add_header X-Frame-Options "SAMEORIGIN" always;

# Control how much information is sent when navigating between origins
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Enable cross-site scripting protection
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' ws: wss:;" always;

# Cache-Control headers will be defined in the main server configuration
# Do not use location blocks in this file 