database:
  url: postgresql+psycopg2://netraven:netraven@localhost:5432/netraven
logging:
  level: DEBUG

worker:
  thread_pool_size: 5           # As per SOT example
  connection_timeout: 15        # As per SOT example (Note: Not yet used in netmiko_driver)
  retry_attempts: 2             # As per SOT example
  retry_backoff: 2              # As per SOT example (seconds)
  git_repo_path: /tmp/netraven_git_repo # Use a temporary path for dev/test
  redaction:
    patterns:                   # As per SOT example
      - "password"
      - "secret"
      - "community"
      - "key" 