name: CI

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # or even higher if needed

    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/docker/requirements.txt') }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install pytest
        run: pip install pytest
      
      - name: Install dotenv
        run: pip install dotenv

      - name: Install flake8
        run: pip install flake8
      
      - name: Install requirements
        run: pip install -r docker/requirements.txt -v

      - name: Run flake8 linting
        run: flake8 .
