# Database configuration for NetRaven web service

database:
  # Database type
  type: "sqlite"  # Options: sqlite, postgres, mysql
  
  # SQLite configuration
  sqlite:
    path: "data/netraven.db"
    timeout: 30
    journal_mode: "WAL"  # Options: DELETE, TRUNCATE, PERSIST, MEMORY, WAL, OFF
    
  # PostgreSQL configuration
  postgres:
    host: "localhost"
    port: 5432
    database: "netraven"
    user: "netraven"
    password: "${DB_PASSWORD}"  # Set via environment variable
    ssl_mode: "prefer"  # Options: disable, allow, prefer, require, verify-ca, verify-full
    connection_timeout: 30
    pool_size: 5
    max_overflow: 10
    
  # MySQL configuration
  mysql:
    host: "localhost"
    port: 3306
    database: "netraven"
    user: "netraven"
    password: "${DB_PASSWORD}"  # Set via environment variable
    charset: "utf8mb4"
    connection_timeout: 30
    pool_size: 5
    max_overflow: 10
    
  # Migration settings
  migrations:
    auto_migrate: true
    migrations_dir: "migrations"
    
  # Connection pool settings
  pool:
    min_size: 5
    max_size: 20
    max_idle: 10
    max_age: 1800  # seconds
    
  # Backup settings
  backup:
    enabled: true
    schedule: "0 0 * * *"  # cron format (daily at midnight)
    path: "backups/db"
    retain: 7  # Number of backups to keep 